import React from 'react';
import {
    Ttml2canvas,
    LocalForage,
    DndKit,
    WebSharedWorker,
    WebWorker,
    WebWorkerTableExport,
    WebWorkerImagesCompress,
    WebSocketCom,
    SocketIO
} from './components/Js'
import {
    ChartEvenDistribution,
    ChartGaussianDistribution,
    ChartLogarithmDistribution,
    ChartPoissonDistribution,
    ChartExponentDistribution,
    ChartBinomialDistribution,
    ChartGammaDistribution,
} from './components/Antv/G2'
import {
    Empty,
    StickyPage,
    BackgroundClip,
    CssMask,
    CssVariableAnimation,
    BubbleLoading,
    ImgGraduallyDisappear,
    CssHexagon,
    ConicGradient,
    TextOverflowMarquee,
    MagicalCssEffects,
} from './components/CssAttr'

import {
    Debugger,
    ReactChildren,
    MiniCalendarTest,
    CalendarTest,
    IconTest,
    SpaceTest,
    PortalTest,
    MutateObserverTest,
    CopyToClipboardTest,
    ObserverTest,
    ReactSpringTest
} from './components/MyReact'

export interface RouterConfigItem {
    key: string;
    parentKey?: string
    index?: true
    text?: string;
    template?: null | React.ReactElement;
    link?: string;
    icon: null | React.ReactElement;
    children?: RouterConfigItem[]
}

// 路由配置项
export const routerConfig: RouterConfigItem[] = [
    {
        key: 'js-demo',
        text: 'js-demo',
        link: '/js-demo',
        // template: <Home />,
        icon: null,
        // children: [],
        children: [
            {
                key: 'Ttml2canvas',
                parentKey: 'js-demo',
                index: true,
                text: 'Ttml2canvas',
                link: '/',
                template: <Ttml2canvas />,
                icon: null,
            },
            {
                key: 'LocalForage',
                parentKey: 'js-demo',
                text: 'LocalForage',
                link: 'local-forage',
                template: <LocalForage />,
                icon: null,
            },
            {
                key: 'DndKit',
                parentKey: 'js-demo',
                text: 'DndKit',
                link: 'react-dnd-kit',
                template: <DndKit />,
                icon: null,
            },
            {
                key: 'WebSharedWorker',
                parentKey: 'js-demo',
                text: 'WebSharedWorker',
                link: 'web-shared-worker',
                template: <WebSharedWorker />,
                icon: null,
            },
            {
                key: 'WebWorker',
                parentKey: 'js-demo',
                text: 'WebWorker',
                link: 'web-worker',
                template: <WebWorker />,
                icon: null,
            },
            {
                key: 'WebWorkerTableExport',
                parentKey: 'js-demo',
                text: 'WebWorkerTableExport',
                link: 'web-worker-table-export',
                template: <WebWorkerTableExport />,
                icon: null,
            },
            {
                key: 'WebWorkerImagesCompress',
                parentKey: 'js-demo',
                text: 'WebWorkerImagesCompress',
                link: 'web-worker-images-compress',
                template: <WebWorkerImagesCompress />,
                icon: null,
            },
            {
                key: 'WebSocket',
                parentKey: 'js-demo',
                text: 'WebSocket',
                link: 'web-socket',
                template: <WebSocketCom />,
                icon: null,
            },
            {
                key: 'SocketIO',
                parentKey: 'js-demo',
                text: 'SocketIO',
                link: 'socket-io',
                template: <SocketIO />,
                icon: null,
            },
        ],
    },

    {
        key: 'css-demo',
        text: 'css-demo',
        link: 'css-demo',
        // template: <>about</>,
        icon: null,
        children: [
            {
                key: 'empty',
                parentKey: 'css-demo',
                index: true,
                text: '伪类-empty',
                link: '/',
                template: <Empty />,
                icon: null,
            },
            {
                key: 'sticky',
                parentKey: 'css-demo',
                text: 'position-sticky',
                link: 'sticky',
                template: <StickyPage />,
                icon: null,
            },
            {
                key: 'background-clip',
                parentKey: 'css-demo',
                text: 'background-clip',
                link: 'background-clip',
                template: <BackgroundClip />,
                icon: null,
            },
            {
                key: 'mask',
                parentKey: 'css-demo',
                text: 'mask',
                link: 'mask',
                template: <CssMask />,
                icon: null,
            },
            {
                key: 'variable-animation',
                parentKey: 'css-demo',
                text: '网格动画',
                link: 'variable-animation',
                template: <CssVariableAnimation />,
                icon: null,
            },
            {
                key: 'bubble-loading',
                parentKey: 'css-demo',
                text: '气泡 Loading',
                link: 'bubble-loading',
                template: <BubbleLoading />,
                icon: null,
            },
            {
                key: 'img-gradually-disappear',
                parentKey: 'css-demo',
                text: '图片渐隐消失术',
                link: 'img-gradually-disappear',
                template: <ImgGraduallyDisappear />,
                icon: null,
            },
            {
                key: 'css-hexagon',
                parentKey: 'css-demo',
                text: '六芒星能力图',
                link: 'css-hexagon',
                template: <CssHexagon />,
                icon: null,
            },
            {
                key: 'conic-gradient',
                parentKey: 'css-demo',
                text: '角向渐变',
                link: 'conic-gradient',
                template: <ConicGradient />,
                icon: null,
            },
            {
                key: 'text-overflow-marquee',
                parentKey: 'css-demo',
                text: '不定宽文本溢出跑马灯',
                link: 'text-overflow-marquee',
                template: <TextOverflowMarquee />,
                icon: null,
            },
            {
                key: 'magical-css-effects',
                parentKey: 'css-demo',
                text: 'magical-css-effects',
                link: 'magical-css-effects',
                template: <MagicalCssEffects />,
                icon: null,
            },
        ],
    },

    {
        key: 'antv',
        text: 'antv',
        link: 'antv',
        // template: <>dashboard</>,
        icon: null,
        children: [
            {
                key: 'g2-ChartEvenDistribution',
                parentKey: 'antv',
                index: true,
                text: '概率分布-正态分布',
                link: '/',
                template: <ChartEvenDistribution />,
                icon: null,
            },
            {
                key: 'g2-ChartGaussianDistribution',
                parentKey: 'antv',
                text: '概率分布-高斯分布',
                link: 'g2-ChartGaussianDistribution',
                template: <ChartGaussianDistribution />,
                icon: null,
            },
            {
                key: 'g2-ChartLogarithmDistribution',
                parentKey: 'antv',
                text: '概率分布-对数正态分布',
                link: 'g2-ChartLogarithmDistribution',
                template: <ChartLogarithmDistribution />,
                icon: null,
            },
            {
                key: 'g2-ChartPoissonDistribution',
                parentKey: 'antv',
                text: '概率分布-泊松分布',
                link: 'g2-ChartPoissonDistribution',
                template: <ChartPoissonDistribution />,
                icon: null,
            },
            {
                key: 'g2-ChartExponentDistribution',
                parentKey: 'antv',
                text: '概率分布-指数分布',
                link: 'g2-ChartExponentDistribution',
                template: <ChartExponentDistribution />,
                icon: null,
            },
            {
                key: 'g2-ChartBinomialDistribution',
                parentKey: 'antv',
                text: '概率分布-二项分布',
                link: 'g2-ChartBinomialDistribution',
                template: <ChartBinomialDistribution />,
                icon: null,
            },
            {
                key: 'g2-ChartGammaDistribution',
                parentKey: 'antv',
                text: '概率分布-伽马分布',
                link: 'g2-ChartGammaDistribution',
                template: <ChartGammaDistribution />,
                icon: null,
            },
        ],
    },

    {
        key: 'my-react',
        text: 'my-react',
        link: '/my-react',
        icon: null,
        children: [
            {
                key: 'react-debugger',
                parentKey: 'my-react',
                index: true,
                text: 'react-debugger',
                link: '/',
                template: <Debugger />,
                icon: null,
            },
            {
                key: 'react-children',
                parentKey: 'my-react',
                text: 'ReactChildren',
                link: 'react-children',
                template: <ReactChildren />,
                icon: null,
            },
            {
                key: 'portal-test',
                parentKey: 'my-react',
                text: 'PortalTest',
                link: 'portal-test',
                template: <PortalTest />,
                icon: null,
            },
            {
                key: 'mutate-observer-test',
                parentKey: 'my-react',
                text: 'MutateObserverTest',
                link: 'mutate-observer-test',
                template: <MutateObserverTest />,
                icon: null,
            },
            {
                key: 'copy-to-clipboard-test',
                parentKey: 'my-react',
                text: 'CopyToClipboardTest',
                link: 'copy-to-clipboard-test',
                template: <CopyToClipboardTest />,
                icon: null,
            },
            {
                key: 'mini-calendar',
                parentKey: 'my-react',
                text: 'MiniCalendar',
                link: 'mini-calendar',
                template: <MiniCalendarTest />,
                icon: null,
            },
            {
                key: 'calendar-test',
                parentKey: 'my-react',
                text: 'CalendarTest',
                link: 'calendar-test',
                template: <CalendarTest />,
                icon: null,
            },
            {
                key: 'icon-test',
                parentKey: 'my-react',
                text: 'IconTest',
                link: 'icon-test',
                template: <IconTest />,
                icon: null,
            },
            {
                key: 'space-test',
                parentKey: 'my-react',
                text: 'SpaceTest',
                link: 'space-test',
                template: <SpaceTest />,
                icon: null,
            },
            {
                key: 'observer-test',
                parentKey: 'my-react',
                text: 'ObserverTest',
                link: 'observer-test',
                template: <ObserverTest />,
                icon: null,
            },
            {
                key: 'react-spring-test',
                parentKey: 'my-react',
                text: 'ReactSpringTest',
                link: 'react-spring-test',
                template: <ReactSpringTest />,
                icon: null,
            },
        ]
    },

    // 使用 path="*"" 意味着 "匹配所有路径", 所以我们不需要明确地列出别的路径了。
    {
        key: '404',
        link: '*',
        template: <>404</>,
        icon: null,
        children: [],
    }
]
